"""Stage 2 - profile the raw data before changing anything.

Answers the questions an analyst asks first: is anything missing or duplicated, where does fraud
happen, how do fraud amounts differ, can the balance columns be trusted, and which fraud patterns
can this data support at all. Writes docs/results/01_profile.md.

Run: uv run python scripts/02_profile.py
"""
from common import RESULTS_DIR, connect, md_table

MONEY_OUT = "type IN ('TRANSFER', 'CASH_OUT')"

SECTIONS = [
    ("Size and fraud rate",
     "How big is the data and how rare is fraud?",
     """SELECT count(*) AS transactions, count(DISTINCT nameOrig) AS senders,
               count(DISTINCT nameDest) AS receivers, max(step) AS hours_simulated,
               sum(isFraud) AS fraud_transactions, round(100 * avg(isFraud), 3) AS fraud_pct
        FROM raw_transactions"""),
    ("Missing values and duplicates",
     "Anything to clean before analysis?",
     """SELECT
            sum(CASE WHEN step IS NULL OR type IS NULL OR amount IS NULL OR nameOrig IS NULL
                      OR nameDest IS NULL THEN 1 ELSE 0 END) AS rows_with_missing_values,
            count(*) - count(DISTINCT (step, type, amount, nameOrig, nameDest, oldbalanceOrg,
                newbalanceOrig, oldbalanceDest, newbalanceDest)) AS duplicate_rows,
            sum(CASE WHEN amount = 0 THEN 1 ELSE 0 END) AS zero_amount_rows
        FROM raw_transactions"""),
    ("Fraud by transaction type",
     "Where does fraud happen?",
     """SELECT type, count(*) AS transactions, sum(isFraud) AS fraud, round(100 * avg(isFraud), 3) AS fraud_pct,
               round(sum(amount * isFraud) / 1e6, 1) AS fraud_amount_millions
        FROM raw_transactions GROUP BY type ORDER BY transactions DESC"""),
    ("The simulator's own fraud flag",
     "How well does the existing rule (isFlaggedFraud) catch fraud?",
     """SELECT isFraud AS is_fraud, isFlaggedFraud AS simulator_flag, count(*) AS transactions
        FROM raw_transactions GROUP BY 1, 2 ORDER BY 1, 2"""),
    ("Amounts: fraud vs genuine (money-out transactions)",
     "Are fraud amounts different?",
     f"""SELECT CASE WHEN isFraud = 1 THEN 'Fraud' ELSE 'Genuine' END AS kind, count(*) AS transactions,
               round(median(amount)) AS median_amount, round(quantile_cont(amount, 0.9)) AS p90_amount,
               round(quantile_cont(amount, 0.99)) AS p99_amount, max(amount) AS max_amount,
               sum(CASE WHEN amount = 10000000 THEN 1 ELSE 0 END) AS exactly_10_million
        FROM raw_transactions WHERE {MONEY_OUT} GROUP BY 1 ORDER BY 1"""),
    ("Balances: do they add up? (money-out transactions)",
     "Can the balance columns be trusted?",
     f"""SELECT CASE WHEN isFraud = 1 THEN 'Fraud' ELSE 'Genuine' END AS kind,
               round(100 * avg(CASE WHEN abs(oldbalanceOrg - amount - newbalanceOrig) > 0.01 THEN 1 ELSE 0 END), 1) AS pct_sender_balance_not_adding_up,
               round(100 * avg(CASE WHEN oldbalanceOrg > 0 AND abs(amount - oldbalanceOrg) < 0.01 THEN 1 ELSE 0 END), 1) AS pct_whole_balance_taken,
               round(100 * avg(CASE WHEN amount > 0 AND oldbalanceDest = 0 AND newbalanceDest = 0 THEN 1 ELSE 0 END), 1) AS pct_receiver_balance_unchanged
        FROM raw_transactions WHERE {MONEY_OUT} GROUP BY 1 ORDER BY 1"""),
    ("Fraud by hour of day",
     "Is fraud more likely at certain times? (step 1 is taken as 00:00-00:59 of day 1)",
     """SELECT (step - 1) % 24 AS hour, count(*) AS transactions, sum(isFraud) AS fraud,
               round(100 * avg(isFraud), 2) AS fraud_pct
        FROM raw_transactions GROUP BY 1 ORDER BY 1"""),
    ("Transactions and fraud by day",
     "Is the data evenly spread over the month?",
     """SELECT (step - 1) // 24 + 1 AS day, count(*) AS transactions, sum(isFraud) AS fraud
        FROM raw_transactions GROUP BY 1 ORDER BY 1"""),
    ("Which patterns can this data support?",
     "Repeat customers (needed for 'many transactions in a short time' rules) and linked transfer-then-cash-out chains (mule accounts).",
     """SELECT
            (SELECT count(*) FROM (SELECT nameOrig FROM raw_transactions GROUP BY 1 HAVING count(*) > 1)) AS senders_seen_more_than_once,
            (SELECT count(*) FROM raw_transactions t WHERE t.isFraud = 1 AND t.type = 'TRANSFER'
               AND EXISTS (SELECT 1 FROM raw_transactions c WHERE c.type = 'CASH_OUT' AND c.nameOrig = t.nameDest))
               AS fraud_transfers_followed_by_cash_out_from_receiver,
            (SELECT sum(isFraud) FROM raw_transactions WHERE type = 'TRANSFER') AS fraud_transfers"""),
]


def main() -> None:
    con = connect(read_only=True)
    out = ["# Stage 2 - data profile", "",
           "Generated by scripts/02_profile.py from the raw PaySim data (6.3 million rows).", ""]
    for title, question, sql in SECTIONS:
        df = con.execute(sql).df()
        out += [f"## {title}", "", f"*{question}*", "", md_table(df), ""]
        print(f"done: {title}")
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    (RESULTS_DIR / "01_profile.md").write_text("\n".join(out), encoding="utf-8")
    con.close()


if __name__ == "__main__":
    main()
