"""Stage 5 - evaluate the rules and export the tables for Power BI.

Plain-language measures used throughout:
  * precision = of the alerts raised, the share that were real fraud (low = many false alarms);
  * recall    = of all real fraud, the share we raised an alert for (low = fraud slips through).

Writes docs/results/02_evaluation.md and CSV files in powerbi/data/.
Run: uv run python scripts/04_evaluate.py
"""
import pandas as pd

from common import POWERBI_DATA, RESULTS_DIR, connect, md_table

RULES = [
    ("R1", "r1_account_emptied", "Account emptied"),
    ("R2", "r2_receiver_unchanged", "Receiver balance unchanged"),
    ("R3", "r3_night_time", "Night time (00:00-06:59)"),
    ("R4", "r4_large_amount", "Large amount (1,000,000+)"),
    ("R5", "r5_zero_amount", "Zero-amount test"),
    ("R6", "r6_new_receiver", "New receiver"),
]
MONEY_OUT = "WHERE is_money_out"


def rule_performance(con):
    parts = [f"""
        SELECT '{rid}' AS rule_id, '{label}' AS rule, sum({col}::INT) AS alerts_if_used_alone,
               sum(({col} AND is_fraud = 1)::INT) AS fraud_caught,
               sum(({col} AND is_fraud = 0)::INT) AS false_alarms,
               round(100.0 * sum(({col} AND is_fraud = 1)::INT) / nullif(sum({col}::INT), 0), 1) AS precision_pct,
               round(100.0 * sum(({col} AND is_fraud = 1)::INT) / sum(is_fraud), 1) AS recall_pct
        FROM scored {MONEY_OUT}""" for rid, col, label in RULES]
    return con.execute(" UNION ALL ".join(parts) + " ORDER BY rule_id").df()


def thresholds(con, score_col, label):
    return con.execute(f"""
        SELECT '{label}' AS scenario, th AS threshold,
               sum((s.{score_col} >= th)::INT) AS alerts,
               round(sum((s.{score_col} >= th)::INT) / 31.0) AS alerts_per_day,
               sum((s.{score_col} >= th AND is_fraud = 1)::INT) AS fraud_caught,
               round(100.0 * sum((s.{score_col} >= th AND is_fraud = 1)::INT) / nullif(sum((s.{score_col} >= th)::INT), 0), 1) AS precision_pct,
               round(100.0 * sum((s.{score_col} >= th AND is_fraud = 1)::INT) / sum(is_fraud), 1) AS recall_pct,
               round(100.0 * sum(CASE WHEN s.{score_col} >= th AND is_fraud = 1 THEN amount ELSE 0 END)
                     / sum(CASE WHEN is_fraud = 1 THEN amount ELSE 0 END), 1) AS fraud_money_caught_pct
        FROM scored s, (SELECT unnest([25, 30, 40, 50, 60]) AS th) {MONEY_OUT}
        GROUP BY th ORDER BY th""").df()


def main() -> None:
    con = connect(read_only=True)

    summary = con.execute(f"""
        SELECT count(*) AS money_out_transactions,
               sum(is_fraud) AS real_fraud,
               sum(is_alert::INT) AS alerts,
               sum((is_alert AND is_fraud = 1)::INT) AS fraud_caught,
               sum((is_alert AND is_fraud = 0)::INT) AS false_alarms,
               sum((NOT is_alert AND is_fraud = 1)::INT) AS fraud_missed,
               round(100.0 * sum((is_alert AND is_fraud = 1)::INT) / sum(is_alert::INT), 1) AS precision_pct,
               round(100.0 * sum((is_alert AND is_fraud = 1)::INT) / sum(is_fraud), 1) AS recall_pct,
               round(sum(CASE WHEN is_alert AND is_fraud = 1 THEN amount ELSE 0 END) / 1e6, 1) AS fraud_money_caught_millions,
               round(sum(CASE WHEN is_fraud = 1 THEN amount ELSE 0 END) / 1e6, 1) AS fraud_money_total_millions,
               sum(simulator_flag) AS caught_by_simulator_flag
        FROM scored {MONEY_OUT}""").df()

    by_priority = con.execute("""
        SELECT priority, count(*) AS alerts, sum(is_fraud) AS real_fraud,
               round(100.0 * avg(is_fraud), 1) AS precision_pct
        FROM scored WHERE is_alert GROUP BY priority
        ORDER BY CASE priority WHEN 'High' THEN 1 WHEN 'Medium' THEN 2 ELSE 3 END""").df()

    rules = rule_performance(con)
    th = thresholds(con, "risk_score", "All rules")
    th_without = thresholds(con, "risk_score_without_r1", "Without R1 (stress test)")

    out = ["# Stage 5 - evaluation", "",
           "Generated by scripts/04_evaluate.py. Money-out transactions only (TRANSFER and CASH_OUT).", "",
           "*Precision* = of the alerts, the share that were real fraud. "
           "*Recall* = of all real fraud, the share that got an alert.", "",
           "## Result at the chosen threshold (risk score 30 or more)", "", md_table(summary), "",
           "## Alerts by priority", "", md_table(by_priority), "",
           "## Each rule on its own", "", md_table(rules), "",
           "## Choosing the threshold: all rules", "", md_table(th), "",
           "## Stress test: the same rules without R1", "",
           "R1 is perfect in this simulated data (no genuine customer ever empties their account in "
           "one go), which would not hold in real life. This shows what the other rules achieve alone.", "",
           md_table(th_without), ""]
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    (RESULTS_DIR / "02_evaluation.md").write_text("\n".join(out), encoding="utf-8")

    # ---- tables for Power BI ----
    POWERBI_DATA.mkdir(parents=True, exist_ok=True)
    con.execute(f"""COPY (
        SELECT txn_id, day, hour, type, amount, sender_id, receiver_id, receiver_kind,
               sender_balance_before, sender_balance_after, receiver_balance_before, receiver_balance_after,
               risk_score, risk_score_without_r1, priority, reasons,
               r1_account_emptied, r2_receiver_unchanged, r3_night_time, r4_large_amount, r5_zero_amount, r6_new_receiver,
               CASE WHEN is_fraud = 1 THEN 'Confirmed fraud' ELSE 'False alarm' END AS outcome
        FROM scored WHERE is_alert ORDER BY risk_score DESC, amount DESC
    ) TO '{(POWERBI_DATA / "alerts.csv").as_posix()}' (HEADER)""")
    con.execute(f"""COPY (
        SELECT txn_id, day, hour, type, amount, sender_id, receiver_id, risk_score, reasons
        FROM scored WHERE is_fraud = 1 AND NOT is_alert ORDER BY amount DESC
    ) TO '{(POWERBI_DATA / "missed_fraud.csv").as_posix()}' (HEADER)""")
    con.execute(f"""COPY (
        SELECT day, hour, type,
               count(*) AS transactions, sum(amount) AS amount,
               sum(is_fraud) AS fraud_transactions, sum(amount * is_fraud) AS fraud_amount,
               sum(is_alert::INT) AS alerts,
               sum((is_alert AND is_fraud = 1)::INT) AS alerts_confirmed_fraud,
               sum((is_alert AND is_fraud = 0)::INT) AS false_alarms,
               sum((NOT is_alert AND is_fraud = 1)::INT) AS fraud_missed,
               sum(CASE WHEN is_alert AND is_fraud = 1 THEN amount ELSE 0 END) AS fraud_amount_caught
        FROM scored GROUP BY day, hour, type ORDER BY day, hour, type
    ) TO '{(POWERBI_DATA / "summary_by_day_hour_type.csv").as_posix()}' (HEADER)""")
    rules.to_csv(POWERBI_DATA / "rule_performance.csv", index=False)
    pd.concat([th, th_without]).to_csv(POWERBI_DATA / "threshold_analysis.csv", index=False)
    con.execute("SELECT * FROM rule_catalogue").df().to_csv(POWERBI_DATA / "rule_catalogue.csv", index=False)

    print(summary.T.to_string(header=False))
    print(by_priority.to_string(index=False))
    con.close()


if __name__ == "__main__":
    main()
